### ISSUE TITLE
Adding database mongoDB with nodeJS/Express

### ISSUE THREAD

**Issue by FranzAmoroso** [FranzAmoroso/nodeJs-Express#2]
- Adding database noSQL mongoDB and managing it with nodeJS/Express

**Comment by shankkyy** [comment]
hey hii @FranzAmoroso can u please tell me more about this issue I want to work on this issue

**Comment by FranzAmoroso** [comment]
Hi @shankkyy This issue provides optimized example code and documentation covering the implementation and execution of the mongoDB database with nodeJs/express and various libraries.

**Comment by shankkyy** [comment]
I've done projects in MERN and also faced lots of issues during the connectivity and fixing and debugging excites me so can you please assign me this issue so that I can give it my best try

**Comment by FranzAmoroso** [comment]
I'm glad you're very enthusiastic about starting a new job, unfortunately this project is now finished, it's just a bit of documentation, instead I have a continental-level project in mind for students entering the world of university, If you would like to participate I will add you to the team and give you tasks

Inviato da iPhone

Il giorno 27.05.2024, alle ore 14:20, shankkyy ***@***.***> ha scritto:

﻿

I've done projects in MERN and also faced lots of issues during the connectivity and fixing and debugging excites me so can you please assign me this issue so that I can give it my best try

**Comment by shankkyy** [comment]
yes I'm interested
